<script lang="ts">
  import type { ModifierKey } from "./types";
  export let value = ""; export let onChange: (value: string) => void; export let label = "录制快捷键"; export let english = false;
  const order: ModifierKey[] = ["ctrl", "alt", "shift", "win"]; const names: Record<ModifierKey,string> = { ctrl: "Ctrl", alt: "Alt", shift: "Shift", win: "Win" };
  let recording = false; let captured = ""; let root: HTMLButtonElement;
  function mods(e: KeyboardEvent) { return order.filter(k => (k === "ctrl" && e.ctrlKey) || (k === "alt" && e.altKey) || (k === "shift" && e.shiftKey) || (k === "win" && e.metaKey)); }
  function name(e: KeyboardEvent) { if (e.key.length === 1) return e.key.toUpperCase(); return ({ " ": "Space", Escape: "Esc", ArrowUp: "Up", ArrowDown: "Down", ArrowLeft: "Left", ArrowRight: "Right", Enter: "Enter", Tab: "Tab" } as Record<string,string>)[e.key] ?? e.key; }
  function start() { recording = true; captured = ""; root.focus(); }
  function keydown(e: KeyboardEvent) { if (!recording) return; e.preventDefault(); e.stopPropagation(); if (e.key === "Escape") { recording = false; captured = ""; return; } const m = mods(e); if (["Control", "Alt", "Shift", "Meta"].includes(e.key)) { captured = m.map(k => names[k]).join("+"); return; } if (!m.length) return; const next = [...m.map(k => names[k]), name(e)].join("+"); captured = next; recording = false; onChange(next); }
  function clear(e: MouseEvent) { e.stopPropagation(); recording = false; captured = ""; onChange(""); }
</script>
<div class:recording class="shortcut-recorder"><button bind:this={root} aria-label={label} on:click={start} on:keydown={keydown} type="button">{#if recording && captured}<span class="key-row">{#each captured.split("+") as key}<kbd>{key}</kbd>{/each}</span>{:else if value}<span class="key-row">{#each value.split("+") as key}<kbd>{key}</kbd>{/each}</span>{:else}<span class="empty">{recording ? (english ? "Press shortcut" : "请按快捷键") : (english ? "Record shortcut" : "点击录制快捷键")}</span>{/if}</button>{#if value}<button class="clear" aria-label={english ? "Clear shortcut" : "清除快捷键"} on:click={clear} type="button">×</button>{/if}</div>
<style>
.shortcut-recorder{min-width:0;display:grid;grid-template-columns:minmax(0,1fr) 30px;gap:6px}.shortcut-recorder:not(:has(.clear)){grid-template-columns:1fr}.shortcut-recorder>button:first-child{height:38px;min-width:0;padding:5px 9px;border:1px solid var(--line-strong);border-radius:6px;background:var(--bg);color:var(--ink);display:flex;align-items:center;justify-content:flex-start}.shortcut-recorder>button:first-child:hover,.shortcut-recorder.recording>button:first-child{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-bg)}.key-row{display:flex;gap:4px;overflow:hidden}.key-row kbd{min-width:28px;height:24px;padding:0 6px;border:1px solid var(--line-strong);border-bottom-width:2px;border-radius:4px;background:var(--surface);font:600 11px/21px "Segoe UI Variable",sans-serif;text-align:center}.empty{color:var(--muted);font-size:12px}.clear{width:30px;height:30px;border:1px solid var(--line);background:transparent;color:var(--muted);font-size:18px}.clear:hover{color:var(--danger);border-color:var(--danger)}
</style>
